import { StyleSheet, Dimensions } from "react-native";
const {height: SCREEN_HEIGHT } = Dimensions.get("window");
export const DRAWER_HEIGHT = SCREEN_HEIGHT * 0.88;

export const C = {
  primary: "#055075",
  accent: "#055075",
  border: "#D8DDE6",
  borderFocus: "#055075",
  bg: "#FFFFFF",
  text: "#1A1A2E",
  muted: "#8A96A8",
  error: "#D93025",
  divider: "#E8ECF2",
  dark: "#2C2C2E",
};

export const styles = StyleSheet.create({
  bgPage: { flex: 1,
     backgroundColor: "#1a1a2e",
    justifyContent: "center", 
    alignItems: "center" },
  bgText: { color: "#fff", 
    fontSize: 28, 
    fontWeight: "bold", 
    opacity: 0.4 },

  drawerOverlay: { position: "absolute", 
    top: 0, 
    left: 0, 
    right: 0, 
    bottom: 0, 
    backgroundColor: "rgba(0,0,0,0.75)" },
  drawerContainer: {
    position: "absolute", 
    bottom: -140, left: 0, right: 0,
    height: DRAWER_HEIGHT, 
    backgroundColor: "#f5f5f5",
    borderTopLeftRadius: 20, 
    borderTopRightRadius: 20,
    overflow: "hidden", 
    elevation: 20,
  },
  dragHandleArea: { width: "100%", 
    alignItems: "center", 
    paddingVertical: 12, 
    backgroundColor: "#f5f5f5" },
  dragHandle: { width: 100, height: 6, 
    backgroundColor: "#d00000", 
    borderRadius: 20 },

  section: { backgroundColor: "#ececec", padding: 16 },
  titleRow: { flexDirection: "row", 
    alignItems: "center", 
    marginBottom: 14 },
  sectionTitle: { fontSize: 22, 
    fontWeight: "600", 
    marginLeft: 10, color: "#111" },
  bioContainer: { flexDirection: "row" },
  formContainer: { flex: 1, 
    flexDirection: "row", 
    flexWrap: "wrap", 
    gap: 8 },
  fieldWrapper: { width: "31.5%" },

  inputBox: {
    width: "100%", 
    height: 56, 
    backgroundColor: "#fff",
    borderRadius: 10, 
    borderWidth: 1, 
    borderColor: "#1976d2",
    paddingHorizontal: 10, 
    justifyContent: "flex-end", 
    paddingBottom: 6,
  },
  inputBoxFocused: { borderColor: "#1976d2", 
    borderWidth: 2 },
  floatingLabel: { position: "absolute", 
    left: 10, 
    fontWeight: "600", 
    backgroundColor: "transparent" },
  inputField: { fontSize: 15, 
    color: "#111", 
    padding: 0, 
    margin: 0, 
    height: 24 },
  dropdownRow: { flexDirection: "row", 
    alignItems: "center", 
    justifyContent: "space-between" },
  inputError: { borderColor: "#d00000", borderWidth: 1.5 },
  errorText: { color: "#d00000", 
    fontSize: 14, 
    marginTop: 2, 
    marginLeft: 2 },

  avatarSection: { width: 100, 
    alignItems: "center", 
    justifyContent: "center" },
  avatar: { width: 90, 
    height: 90, 
    borderRadius: 45, 
    backgroundColor: "#bdbdbd", 
    justifyContent: "center", 
    alignItems: "center", 
    marginTop: -50 },
  avatarImage: { width: 90, 
    height: 90, 
    borderRadius: 45 },
  cameraBtn: { position: "absolute", 
    bottom: 0, 
    right: 0, 
    backgroundColor: "#666", 
    width: 28, height: 28, 
    borderRadius: 14, 
    justifyContent: "center", 
    alignItems: "center" },

  modalOverlay: { flex: 1, 
    backgroundColor: "rgba(0,0,0,0.3)", 
    justifyContent: "center", 
    alignItems: "center" },
  dropdown: { backgroundColor: "#fff", 
    borderRadius: 10, 
    width: 200, 
    maxHeight: 200, 
    elevation: 5 },
  dropdownItem: { padding: 14, 
    borderBottomWidth: 1, 
    borderBottomColor: "#eee" },
  dropdownItemText: { fontSize: 15, 
    color: "#111" },

  pickerModal: { backgroundColor: "#fff", 
    borderRadius: 16, 
    width: 280, 
    paddingVertical: 8, 
    elevation: 10 },
  pickerTitle: { fontSize: 16, 
    fontWeight: "700", 
    textAlign: "center", 
    paddingVertical: 14, 
    color: "#111", 
    borderBottomWidth: 1, 
    borderBottomColor: "#eee" },
  pickerOption: { flexDirection: "row", 
    alignItems: "center", 
    paddingVertical: 16, 
    paddingHorizontal: 24, 
    gap: 14 },
  pickerOptionText: { fontSize: 16, 
    color: "#111" },
  pickerDivider: { height: 1, 
    backgroundColor: "#eee", 
    marginHorizontal: 16 },
  pickerCancel: { marginTop: 4, 
    borderTopWidth: 1, 
    borderTopColor: "#eee", 
    paddingVertical: 14, 
    alignItems: "center" },
  pickerCancelText: { fontSize: 15, 
    color: "#d00000", 
    fontWeight: "600" },

  middleContainer: { flexDirection: "row", 
    backgroundColor: "#fff" },
  leftColumn: { flex: 1, 
    padding: 16, 
    borderRightWidth: 1, borderColor: "#ddd" },
  rightColumn: { flex: 1, padding: 16 },

  membershipCard: { flexDirection: "row", 
    backgroundColor: "#ecffe9", 
    borderRadius: 14, 
    padding: 14, 
    marginBottom: 20, 
    alignItems: "center", 
    elevation: 2 },
  planTitle: { color: "#888", 
    fontWeight: "600", 
    fontSize: 11 },
  planName: { fontSize: 18, 
    fontWeight: "600", 
    marginTop: 2 },
  price: { color: "#ff3333", 
    fontWeight: "bold", 
    marginTop: 8, 
    fontSize: 13 },
  verticalLine: { width: 1, 
    height: 60, 
    backgroundColor: "#ff3333", 
    marginHorizontal: 12 },
  smallHeading: { color: "#d32f2f", 
    fontWeight: "600", 
    fontSize: 12 },
  smallValue: { marginTop: 8, 
    fontWeight: "500", 
    fontSize: 13 },

  upiCard: { height: 90, 
    backgroundColor: "#d9efff", 
    borderRadius: 12, 
    justifyContent: "center", 
    alignItems: "center", 
    marginBottom: 16 },
  upiLogo: { width: 120, 
    height: 50, 
 },
  couponInput: { height: 46, 
    borderWidth: 1, 
    borderColor: "#2ecc71", 
    borderRadius: 10, 
    paddingHorizontal: 12, 
    fontSize: 14 },

  billRow: { flexDirection: "row", 
    justifyContent: "space-between", 
    marginBottom: 18 },
  billText: { fontSize: 17 },
  billAmount: { fontSize: 19, 
    fontWeight: "bold" },
  discount: { fontSize: 19, 
    color: "#00c853", 
    fontWeight: "bold" },
  payBtn: { backgroundColor: "#00a11b", 
    height: 52, 
    borderRadius: 26, 
    justifyContent: "center", 
    alignItems: "center", 
    marginTop: 16 },
  payText: { color: "#fff", 
    fontSize: 20, 
    fontWeight: "bold" },
});