import { StyleSheet, Dimensions } from 'react-native';
import { COLORS } from '../../styles/global-style-sheet';
const {height: SCREEN_HEIGHT } = Dimensions.get("window");
export const DRAWER_HEIGHT = SCREEN_HEIGHT * 0.88;

const { width: SCREEN_WIDTH } = Dimensions.get('window');

// Central color palette for the dashboard. Tweak these to match
// the brand kit exactly once you have hex values from design.


const SCREEN_PADDING = 16;
const CARD_GAP = 12;
const CARD_WIDTH = (SCREEN_WIDTH - SCREEN_PADDING * 2 - CARD_GAP) / 2;

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.screenBg,
  },
  scrollContent: {
    paddingBottom: 112,
  },

  heroShell: {
    marginHorizontal: 0,
    marginTop: 0,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: COLORS.primaryDark,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },

  // ---------- Banner ads ----------
  bannerWrapper: {
    width: SCREEN_WIDTH,
    height: 220,
  },
  bannerSlide: {
    width: SCREEN_WIDTH,
    height: 220,
    justifyContent: 'flex-start',
    paddingHorizontal: 24,
    paddingTop: 28,
  },
  bannerTitle: {
    color: COLORS.white,
    fontSize: 24,
    fontWeight: '800',
    fontFamily: 'Nunito_800ExtraBold',
    maxWidth: 230,
  },
  bannerSubtitle: {
    color: COLORS.white,
    fontSize: 13,
    marginTop: 6,
    opacity: 0.9,
    fontFamily: 'Nunito_600SemiBold',
    maxWidth: 220,
  },
  dotsContainer: {
    position: 'absolute',
    bottom: 12,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  dot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: 'rgba(255,255,255,0.45)',
    marginHorizontal: 3,
  },
  dotActive: {
    backgroundColor: COLORS.white,
    width: 18,
  },

  // ---------- "Top Memberships" quick strip ----------
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: SCREEN_PADDING,
    marginTop: 18,
    marginBottom: 10,
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionHeaderAccent: {
    width: 4,
    height: 18,
    borderRadius: 2,
    backgroundColor: COLORS.accent,
    marginRight: 8,
  },
  sectionHeaderTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: COLORS.textDark,
    letterSpacing: 0.3,
    fontFamily: 'Nunito_800ExtraBold',
  },
  seeAllText: {
    fontSize: 14,
    color: COLORS.primary,
    fontWeight: '600',
    fontFamily: 'Nunito_700Bold',
  },
  stripContent: {
    paddingHorizontal: SCREEN_PADDING,
    paddingBottom: 4,
  },
  stripCard: {
    width: 200,
    backgroundColor: COLORS.cardBackground,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 16,
    marginRight: 12,
    elevation: 1,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  stripBadge: {
    alignSelf: 'flex-start',
    backgroundColor: COLORS.accent,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginBottom: 6,
  },
  stripBadgeText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '700',
  },
  stripCardTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.textDark,
    fontFamily: 'Nunito_700Bold',
  },
  stripCardPlan: {
    fontSize: 14,
    color: COLORS.mutedText,
    marginTop: 2,
    fontFamily: 'Nunito_600SemiBold',
  },
  stripCardPrice: {
    fontSize: 17,
    fontWeight: '700',
    color: COLORS.primary,
    marginTop: 4,
    fontFamily: 'Nunito_800ExtraBold',
  },

  // ---------- Category sections (Gym Workout, PT, Group Exercise, Liberty) ----------
  categorySection: {
    marginTop: 16,
    paddingHorizontal: SCREEN_PADDING,
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  categoryHeaderText: {
    marginLeft: 8,
  },
  categoryTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.textDark,
    fontFamily: 'Nunito_800ExtraBold',
  },
  categorySubtitle: {
    fontSize: 15,
    color: COLORS.mutedText,
    marginTop: 1,
    fontFamily: 'Nunito_400Regular',
  },
  plansGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  planCard: {
    width: CARD_WIDTH,
    backgroundColor: COLORS.cardBackground,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'transparent',
    padding: 20,
    marginBottom: CARD_GAP,
    minHeight: 160,
    justifyContent: 'flex-start',
    shadowColor: '#0B2340',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  planCardSelected: {
    borderWidth: 2,
    borderColor: '#0D2B52',
  },
  cardHeaderRow: {
    height: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: 8,
  },
  popularBadge: {
    alignSelf: 'flex-start',
    backgroundColor: COLORS.accent,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginBottom: 6,
  },
  popularBadgeText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: '700',
  },
  // popularBadgePlaceholder: {
  //   minWidth: 54,
  // },
  checkBoxBox: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#B7C6D3',
    backgroundColor: 'rgba(255,255,255,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkBoxBoxSelected: {
    backgroundColor: '#0D2B52',
    borderColor: '#0D2B52',
  },
  durationLabel: {
    fontSize: 17,
    color: COLORS.mutedText,
    textTransform: 'uppercase',
    fontWeight: '700',
    marginBottom: 6,
  },
  durationRow: {            
    flexDirection: 'row',
    alignItems: 'center',
    gap:8,
    marginBottom: 6,         
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  priceMain: {
    fontSize: 22,
    color: COLORS.primary,
    fontWeight: '800',
  },
  priceUnit: {
    fontSize: 16,
    color: COLORS.mutedText,
    marginLeft: 6,
  },
  subPrice: {
    fontSize: 15,
    color: COLORS.mutedText,
    marginTop: 6,
  },
  buyButtonFull: {
    backgroundColor: '#E6EDF4',
    borderRadius: 999,
    paddingVertical: 10,
    alignItems: 'center',
    marginTop: 12,
  },
  buyButtonFullText: {
    color: '#2F3A44',
    fontSize: 18,
    fontWeight: '700',
  },
  bannerTextBlock: {
    flex: 1,
    justifyContent: 'center',
  },
  planBadge: {
    position: 'absolute',
    top: 8,
    left: 10,
    backgroundColor: COLORS.accent,
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  planBadgeText: {
    color: COLORS.white,
    fontSize: 9,
    fontWeight: '700',
    fontFamily: 'Nunito_700Bold',
  },
  planCheckBox: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#B7C6D3',
    backgroundColor: 'rgba(255,255,255,0.45)',
  },
  planLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.mutedText,
    marginTop: 20,
    fontFamily: 'Nunito_700Bold',
  },
  planPrice: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.textDark,
    fontFamily: 'Nunito_800ExtraBold',
  },
  planPriceLine: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginTop: 4,
  },
  planPriceSuffix: {
    fontSize: 10,
    color: COLORS.mutedText,
    marginLeft: 4,
    fontFamily: 'Nunito_600SemiBold',
  },
  planSecondary: {
    fontSize: 10,
    color: COLORS.mutedText,
    marginTop: 2,
    fontFamily: 'Nunito_400Regular',
  },
  buyButton: {
    backgroundColor: '#DDE6EF',
    borderRadius: 999,
    paddingVertical: 7,
    alignItems: 'center',
    marginTop: 'auto',
  },
  buyButtonText: {
    color: '#4B5563',
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'Nunito_700Bold',
  },

  // ---------- Floating action button ----------
  fab: {
    position: 'absolute',
    right: 20,
    bottom:100,
    width: 180,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.accent,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  fabButton: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
},

fabText: {
  color: COLORS.white,
  fontSize: 16,
  fontWeight: '700',
  marginLeft: 8,
},

  selectionSummaryBar: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 16,
    backgroundColor: '#0D2B52',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  selectionSummaryCount: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '700',
    fontFamily: 'Nunito_700Bold',
  },
  selectionSummaryTotal: {
    color: COLORS.white,
    fontSize: 16,
    marginTop: 2,
    fontWeight: '800',
    fontFamily: 'Nunito_800ExtraBold',
  },
  selectionSummaryNextButton: {
    backgroundColor: COLORS.white,
    borderRadius: 999,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  selectionSummaryNextText: {
    color: '#0D2B52',
    fontSize: 13,
    fontWeight: '800',
    fontFamily: 'Nunito_800ExtraBold',
  },

  // ---------- Splash screen ads (attract / idle screen) ----------
  splashOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  splashContent: {
    alignItems: 'center',
  },
  splashTitle: {
    color: COLORS.white,
    fontSize: 26,
    fontWeight: '800',
    textAlign: 'center',
  },
  splashSubtitle: {
    color: COLORS.white,
    fontSize: 14,
    marginTop: 8,
    textAlign: 'center',
    opacity: 0.9,
  },
  splashHint: {
    position: 'absolute',
    bottom: 40,
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
  },
});



export const C = {
  primary: "#055075",
  accent: "#055075",
  border: "#D8DDE6",
  borderFocus: "#055075",
  bg: "#FFFFFF",
  text: "#1A1A2E",
  muted: "#8A96A8",
  error: "#D93025",
  divider: "#E8ECF2",
  dark: "#2C2C2E",
};

export const styles = StyleSheet.create({
  bgPage: { flex: 1,
     backgroundColor: "#1a1a2e",
    justifyContent: "center", 
    alignItems: "center" },
  bgText: { color: "#fff", 
    fontSize: 28, 
    fontWeight: "bold", 
    opacity: 0.4 },

  drawerOverlay: { position: "absolute", 
    top: 0, 
    left: 0, 
    right: 0, 
    bottom: 0, 
    backgroundColor: "rgba(0,0,0,0.75)" },
  drawerContainer: {
    position: "absolute", 
    bottom: -140, left: 0, right: 0,
    height: DRAWER_HEIGHT, 
    backgroundColor: "#f5f5f5",
    borderTopLeftRadius: 20, 
    borderTopRightRadius: 20,
    overflow: "hidden", 
    elevation: 20,
  },
  dragHandleArea: { width: "100%", 
    alignItems: "center", 
    paddingVertical: 12, 
    backgroundColor: "#f5f5f5" },
  dragHandle: { width: 100, height: 6, 
    backgroundColor: "#d00000", 
    borderRadius: 20 },

  section: { backgroundColor: "#ececec", padding: 16 },
  titleRow: { flexDirection: "row", 
    alignItems: "center", 
    marginBottom: 14 },
  sectionTitle: { fontSize: 22, 
    fontWeight: "600", 
    marginLeft: 10, color: "#111" },
  bioContainer: { flexDirection: "row" },
  formContainer: { flex: 1, 
    flexDirection: "row", 
    flexWrap: "wrap", 
    gap: 8 },
  fieldWrapper: { width: "31.5%" },

  inputBox: {
    width: "100%", 
    height: 56, 
    backgroundColor: "#fff",
    borderRadius: 10, 
    borderWidth: 1, 
    borderColor: "#1976d2",
    paddingHorizontal: 10, 
    justifyContent: "flex-end", 
    paddingBottom: 6,
  },
  inputBoxFocused: { borderColor: "#1976d2", 
    borderWidth: 2 },
  floatingLabel: { position: "absolute", 
    left: 10, 
    fontWeight: "600", 
    backgroundColor: "transparent" },
  inputField: { fontSize: 15, 
    color: "#111", 
    padding: 0, 
    margin: 0, 
    height: 24 },
  dropdownRow: { flexDirection: "row", 
    alignItems: "center", 
    justifyContent: "space-between" },
  inputError: { borderColor: "#d00000", borderWidth: 1.5 },
  errorText: { color: "#d00000", 
    fontSize: 14, 
    marginTop: 2, 
    marginLeft: 2 },

  avatarSection: { width: 100, 
    alignItems: "center", 
    justifyContent: "center" },
  avatar: { width: 90, 
    height: 90, 
    borderRadius: 45, 
    backgroundColor: "#bdbdbd", 
    justifyContent: "center", 
    alignItems: "center", 
    marginTop: -50 },
  avatarImage: { width: 90, 
    height: 90, 
    borderRadius: 45 },
  cameraBtn: { position: "absolute", 
    bottom: 0, 
    right: 0, 
    backgroundColor: "#666", 
    width: 28, height: 28, 
    borderRadius: 14, 
    justifyContent: "center", 
    alignItems: "center" },

  modalOverlay: { flex: 1, 
    backgroundColor: "rgba(0,0,0,0.3)", 
    justifyContent: "center", 
    alignItems: "center" },
  dropdown: { backgroundColor: "#fff", 
    borderRadius: 10, 
    width: 200, 
    maxHeight: 200, 
    elevation: 5 },
  dropdownItem: { padding: 14, 
    borderBottomWidth: 1, 
    borderBottomColor: "#eee" },
  dropdownItemText: { fontSize: 15, 
    color: "#111" },

  pickerModal: { backgroundColor: "#fff", 
    borderRadius: 16, 
    width: 280, 
    paddingVertical: 8, 
    elevation: 10 },
  pickerTitle: { fontSize: 16, 
    fontWeight: "700", 
    textAlign: "center", 
    paddingVertical: 14, 
    color: "#111", 
    borderBottomWidth: 1, 
    borderBottomColor: "#eee" },
  pickerOption: { flexDirection: "row", 
    alignItems: "center", 
    paddingVertical: 16, 
    paddingHorizontal: 24, 
    gap: 14 },
  pickerOptionText: { fontSize: 16, 
    color: "#111" },
  pickerDivider: { height: 1, 
    backgroundColor: "#eee", 
    marginHorizontal: 16 },
  pickerCancel: { marginTop: 4, 
    borderTopWidth: 1, 
    borderTopColor: "#eee", 
    paddingVertical: 14, 
    alignItems: "center" },
  pickerCancelText: { fontSize: 15, 
    color: "#d00000", 
    fontWeight: "600" },

  middleContainer: { flexDirection: "row", 
    backgroundColor: "#fff" },
  leftColumn: { flex: 1, 
    padding: 16, 
    borderRightWidth: 1, borderColor: "#ddd" },
  rightColumn: { flex: 1, padding: 16 },

  membershipCard: { flexDirection: "row", 
    backgroundColor: "#ecffe9", 
    borderRadius: 14, 
    padding: 14, 
    marginBottom: 20, 
    alignItems: "center", 
    elevation: 2 },
  planTitle: { color: "#888", 
    fontWeight: "600", 
    fontSize: 11 },
  planName: { fontSize: 18, 
    fontWeight: "600", 
    marginTop: 2 },
  price: { color: "#ff3333", 
    fontWeight: "bold", 
    marginTop: 8, 
    fontSize: 13 },
  verticalLine: { width: 1, 
    height: 60, 
    backgroundColor: "#ff3333", 
    marginHorizontal: 12 },
  smallHeading: { color: "#d32f2f", 
    fontWeight: "600", 
    fontSize: 12 },
  smallValue: { marginTop: 8, 
    fontWeight: "500", 
    fontSize: 13 },

  upiCard: { height: 90, 
    backgroundColor: "#d9efff", 
    borderRadius: 12, 
    justifyContent: "center", 
    alignItems: "center", 
    marginBottom: 16 },
  upiLogo: { width: 120, 
    height: 50, 
 },
  couponInput: { height: 46, 
    borderWidth: 1, 
    borderColor: "#2ecc71", 
    borderRadius: 10, 
    paddingHorizontal: 12, 
    fontSize: 14 },

  billRow: { flexDirection: "row", 
    justifyContent: "space-between", 
    marginBottom: 18 },
  billText: { fontSize: 17 },
  billAmount: { fontSize: 19, 
    fontWeight: "bold" },
  discount: { fontSize: 19, 
    color: "#00c853", 
    fontWeight: "bold" },
  payBtn: { backgroundColor: "#00a11b", 
    height: 52, 
    borderRadius: 26, 
    justifyContent: "center", 
    alignItems: "center", 
    marginTop: 16 },
  payText: { color: "#fff", 
    fontSize: 20, 
    fontWeight: "bold" },
});


export { COLORS };
